---
title: "Ejercicio_24_02_21(2)"
output: html_document
---

```{r}
## Load recount3 R package
library("recount3")
```

```{r}
## Revisemos todos los proyectos con datos de humano en recount3
human_projects <- available_projects()
```

```{r}
proj_info <- subset(
    human_projects,
    project == "SRP009615" & project_type == "data_sources"
)
```

```{r}
rse_gene_SRP009615 <- create_rse(proj_info)
```

```{r}
assay(rse_gene_SRP009615, "counts") <- compute_read_counts(rse_gene_SRP009615)
```

```{r}
rse_gene_SRP009615 <- expand_sra_attributes(rse_gene_SRP009615)
colData(rse_gene_SRP009615)[
    ,
    grepl("^sra_attribute", colnames(colData(rse_gene_SRP009615)))
]
```

```{r}
iSEE::iSEE(rse_gene_SRP009615)
```

#Se cambian algunos paramteros de la "Feature assay plot 1"

En data parameters se selecciona los sig. parametros:
Y-axis-feature-> Se pone el id de interes, en este cao fue el ENSG00000168314.17
X-axis-> Column data-> sra_attribute.shRNA_expression

En visual parameters se selecciona los sig. parametros:
color by-> column data-> sra_attribute.treatment




